name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create release branch and bump version
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release/${REF:10}
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b $BRANCH
          git push -u origin $BRANCH

      - name: Create release archive
        run: |
          tar -czf main.tar.gz * .gitignore

      - name: Create checksum
        run: |
          SUM=`sha256sum main.tar.gz`
          echo $SUM > checksum.txt

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            main.tar.gz
            checksum.txt
